import { parseGameStatePayload } from './gameStateTransfer';

const BOB_GAME_STATE_PAYLOAD = 'sk2:NoJgNARCAMIGwFpqJAZgCpoFwEYdYBYcA6AdhAFYAtCMYYCAUQBsBLAQwGdboxecAunQgBZVgGMAFqx5gcfIQwBiAUzYAPWghzQK-BcIAi7AHYmAnrPmCjklSoBOVgwwDKKgG4y+chYuDacPzQpLy8qLwEemAIqATQirG8ST68AJzJEYkZYBGpueEJdNrB+ToxOoqlyeXlJYl5YTF5KRmJMGAdyR1dDelNKZlFAXk5Ay1ZdMkAHE0g8TGzi8NdPggd67wwiUGdc1thijhLybsIu6fDkckLCAsLwxS3x001S9qzR68VpfXF5TVSgDFD1vpsYts6Et3vNvp8phUOvcmvFFA8wOjnpDgLd0Xdri5UGccBsSWCyV85EDktFKnRcSibocEbVqs0VgNVuDsWySj8qTteLszhcXACqWs6nTgN9XlUfgMdIDCsNxSlxdKEDktQMciBQi5zgcfKCXKtTZdEqzJdV5RtRaDsrrkmNOqEQWCNo66K71gb+mA2nQ1dbAYlkT4GS5fo0JZqNU0pcM+eLftLjVyvcmE-zgh69ibLn46JTrIcBEA';

export const getBobGameState = () => parseGameStatePayload(BOB_GAME_STATE_PAYLOAD);
